export const siteConfig = {
  name: "APEX",
  fullName: "APEX Performance Studio",
  tagline: "Where limits become starting points.",
  address: "2847 N Clark St, Chicago, IL 60657",
  phone: "(312) 555-0174",
  email: "hello@apexperformancestudio.com",
  instagram: "#",
  hours: {
    weekday: "5:00 AM – 10:00 PM",
    saturday: "6:00 AM – 8:00 PM",
    sunday: "7:00 AM – 6:00 PM",
  },
};

export const classes = [
  {
    id: "hiit-forge",
    name: "HIIT Forge",
    category: "HIIT",
    duration: "45 min",
    intensity: "High",
    description: "Maximum effort, maximum results. Alternating explosive intervals with active recovery to torch calories and build cardiovascular capacity.",
    gradient: "linear-gradient(135deg, #FF4D1C 0%, #FF8C00 100%)",
    schedule: ["Mon 6:00 AM", "Wed 12:00 PM", "Fri 6:00 AM", "Sat 8:00 AM"],
    trainer: "Darnell Banks",
    spots: 16,
  },
  {
    id: "iron-temple",
    name: "Iron Temple",
    category: "Strength",
    duration: "60 min",
    intensity: "Moderate–High",
    description: "Progressive strength training built around compound movements. Barbells, dumbbells, and functional patterns to build real-world power.",
    gradient: "linear-gradient(135deg, #1A1AFF 0%, #7B2FBE 100%)",
    schedule: ["Tue 7:00 AM", "Thu 6:00 PM", "Sat 10:00 AM"],
    trainer: "Marcus Reid",
    spots: 12,
  },
  {
    id: "flow-state",
    name: "Flow State",
    category: "Yoga",
    duration: "60 min",
    intensity: "Low–Moderate",
    description: "Dynamic vinyasa sequences that build flexibility, balance, and mental clarity. Accessible for all levels — bring your breath and leave the rest.",
    gradient: "linear-gradient(135deg, #00C9A7 0%, #007BFF 100%)",
    schedule: ["Mon 7:30 AM", "Wed 6:30 PM", "Fri 12:00 PM", "Sun 9:00 AM"],
    trainer: "Sofia Chen",
    spots: 20,
  },
  {
    id: "velocity-cycle",
    name: "Velocity Cycle",
    category: "Cycling",
    duration: "45 min",
    intensity: "High",
    description: "Rhythm-based indoor cycling set to curated playlists. Every pedal stroke pushes you closer to your best performance — saddle up.",
    gradient: "linear-gradient(135deg, #C8FF00 0%, #00E87C 100%)",
    schedule: ["Tue 6:00 AM", "Thu 12:00 PM", "Sat 7:00 AM", "Sun 8:00 AM"],
    trainer: "Marcus Reid",
    spots: 24,
  },
  {
    id: "combat-ready",
    name: "Combat Ready",
    category: "Boxing",
    duration: "50 min",
    intensity: "High",
    description: "Boxing fundamentals meets full-body conditioning. Bag work, pad drills, and bodyweight circuits that build coordination and serious stamina.",
    gradient: "linear-gradient(135deg, #FF1744 0%, #FF6D00 100%)",
    schedule: ["Mon 6:00 PM", "Wed 7:00 AM", "Fri 6:00 PM"],
    trainer: "Darnell Banks",
    spots: 14,
  },
  {
    id: "recover-reset",
    name: "Recover & Reset",
    category: "Recovery",
    duration: "45 min",
    intensity: "Low",
    description: "Guided mobility, foam rolling, and breathwork designed to accelerate recovery, reduce soreness, and keep you training at full capacity.",
    gradient: "linear-gradient(135deg, #667EEA 0%, #764BA2 100%)",
    schedule: ["Tue 7:30 PM", "Thu 7:00 AM", "Sun 10:30 AM"],
    trainer: "Sofia Chen",
    spots: 18,
  },
];

export const trainers = [
  {
    name: "Marcus Reid",
    title: "Head Strength Coach",
    initials: "MR",
    gradient: "linear-gradient(135deg, #1A1AFF 0%, #7B2FBE 100%)",
    specialty: "Powerlifting · Sports Performance",
    bio: "Former D1 athlete with 10+ years coaching everyone from beginners to competitive powerlifters. Marcus believes strength is the foundation of everything.",
    certifications: ["CSCS", "NSCA-CPT", "FMS Level 2"],
    classes: ["Iron Temple", "Velocity Cycle"],
  },
  {
    name: "Sofia Chen",
    title: "Lead Wellness Coach",
    initials: "SC",
    gradient: "linear-gradient(135deg, #00C9A7 0%, #007BFF 100%)",
    specialty: "Yoga · Mobility · Recovery",
    bio: "200-hr RYT with a background in sports physical therapy. Sofia brings science-backed recovery techniques to every session — your body will thank you.",
    certifications: ["RYT-200", "NASM-CPT", "SFMA"],
    classes: ["Flow State", "Recover & Reset"],
  },
  {
    name: "Darnell Banks",
    title: "HIIT & Combat Specialist",
    initials: "DB",
    gradient: "linear-gradient(135deg, #FF4D1C 0%, #FF8C00 100%)",
    specialty: "HIIT · Boxing · Conditioning",
    bio: "Golden Gloves amateur boxer turned conditioning coach. Darnell's classes are hard — and he'll make sure you love every second of it.",
    certifications: ["NASM-CPT", "USA Boxing Coach", "HIIT Specialist"],
    classes: ["HIIT Forge", "Combat Ready"],
  },
];

export const pricingTiers = [
  {
    name: "Drop-In",
    price: "$28",
    period: "per class",
    description: "No commitment. Show up when you want, for any class on the schedule.",
    features: [
      "Single class access",
      "Any class on schedule",
      "Locker room & showers",
      "Towel service included",
    ],
    cta: "Book a Class",
    highlighted: false,
  },
  {
    name: "Monthly",
    price: "$149",
    period: "per month",
    description: "Unlimited classes, priority booking, and full access to all amenities.",
    features: [
      "Unlimited classes",
      "Priority class booking",
      "1 free guest pass/month",
      "Recovery lounge access",
      "APEX app included",
      "Free nutrition consult",
    ],
    cta: "Start Today",
    highlighted: true,
    badge: "Most Popular",
  },
  {
    name: "Annual",
    price: "$99",
    period: "per month",
    description: "Everything in Monthly — billed yearly. Save $600 and lock in your rate forever.",
    features: [
      "Everything in Monthly",
      "2 free guest passes/month",
      "1 PT session/month ($80 value)",
      "Exclusive member events",
      "Rate locked forever",
    ],
    cta: "Get Best Value",
    highlighted: false,
    badge: "Save $600/yr",
  },
];

export const testimonials = [
  {
    name: "Jasmine T.",
    initials: "JT",
    gradient: "linear-gradient(135deg, #FF4D1C, #FF8C00)",
    rating: 5,
    text: "I've tried every gym in Chicago. APEX is on another level. The classes are challenging but the coaches actually know your name. HIIT Forge has completely transformed my cardio in 3 months.",
    highlight: "Lost 18 lbs in 3 months",
    class: "HIIT Forge",
    date: "January 2026",
  },
  {
    name: "Ryan O.",
    initials: "RO",
    gradient: "linear-gradient(135deg, #1A1AFF, #7B2FBE)",
    rating: 5,
    text: "Marcus in Iron Temple is the best strength coach I've worked with. He corrected form issues I had for years in the first session. My squat went up 40 lbs in two months.",
    highlight: "Squat PR up 40 lbs",
    class: "Iron Temple",
    date: "February 2026",
  },
  {
    name: "Priya M.",
    initials: "PM",
    gradient: "linear-gradient(135deg, #00C9A7, #007BFF)",
    rating: 5,
    text: "Sofia's Flow State class is the only reason I get through my week. The vibe is incredible and I've never been more flexible or less stressed. Plus the recovery lounge is 10/10.",
    highlight: "Zero injuries all season",
    class: "Flow State",
    date: "March 2026",
  },
];

export const stats = [
  { value: "1,200+", label: "Active Members" },
  { value: "40+", label: "Classes Per Week" },
  { value: "8", label: "Elite Coaches" },
  { value: "4.9★", label: "Google Rating" },
];

export const features = [
  {
    icon: "⚡",
    title: "Results-Driven Programming",
    desc: "Every class is periodized and progressive — not just random sweat. You'll see measurable improvement in 30 days or your membership is free.",
  },
  {
    icon: "🧬",
    title: "Recovery Built In",
    desc: "Our recovery lounge, cold plunge, and Recover & Reset classes mean you come back stronger, not broken.",
  },
  {
    icon: "📱",
    title: "APEX App",
    desc: "Book classes, track your PRs, see your workout history, and message coaches — all from your phone.",
  },
  {
    icon: "🏆",
    title: "Elite Coaches Only",
    desc: "Every APEX coach holds at minimum 2 nationally recognized certifications and goes through a 60-hour internal training program.",
  },
];
