export const siteConfig = {
  name: "APEX",
  fullName: "APEX Performance Studio",
  tagline: "An hour at the limit.",
  address: "412 Haddon Ave, Haddon Township, NJ 08108",
  city: "Haddon Township",
  phone: "(856) 555-0174",
  email: "hello@apexperformancestudio.com",
  instagram: "@apexperformancenj",
  hours: {
    weekday: "5:00 AM – 10:00 PM",
    saturday: "6:00 AM – 8:00 PM",
    sunday: "7:00 AM – 6:00 PM",
  },
};

export const classes = [
  {
    id: "hiit-forge",
    name: "HIIT Forge",
    category: "HIIT",
    duration: "45 min",
    intensity: "High",
    description: "Maximum effort, maximum results. Alternating explosive intervals with active recovery to torch calories and build cardiovascular capacity.",
    schedule: ["Mon 6:00 AM", "Wed 12:00 PM", "Fri 6:00 AM", "Sat 8:00 AM"],
    trainer: "Darnell Banks",
    spots: 16,
  },
  {
    id: "iron-temple",
    name: "Iron Temple",
    category: "Strength",
    duration: "60 min",
    intensity: "Moderate–High",
    description: "Progressive strength training built around compound movements. Barbells, dumbbells, and functional patterns to develop real-world power.",
    schedule: ["Tue 7:00 AM", "Thu 6:00 PM", "Sat 10:00 AM"],
    trainer: "Marcus Reid",
    spots: 12,
  },
  {
    id: "flow-state",
    name: "Flow State",
    category: "Yoga",
    duration: "60 min",
    intensity: "Low–Moderate",
    description: "Dynamic vinyasa sequences that build flexibility, balance, and mental clarity. Accessible for all levels — bring your breath and leave the rest.",
    schedule: ["Mon 7:30 AM", "Wed 6:30 PM", "Fri 12:00 PM", "Sun 9:00 AM"],
    trainer: "Sofia Chen",
    spots: 20,
  },
  {
    id: "velocity-cycle",
    name: "Velocity Cycle",
    category: "Cycling",
    duration: "45 min",
    intensity: "High",
    description: "Rhythm-based indoor cycling set to curated playlists. Every pedal stroke pushes you closer to your best performance — saddle up.",
    schedule: ["Tue 6:00 AM", "Thu 12:00 PM", "Sat 7:00 AM", "Sun 8:00 AM"],
    trainer: "Marcus Reid",
    spots: 24,
  },
  {
    id: "combat-ready",
    name: "Combat Ready",
    category: "Boxing",
    duration: "50 min",
    intensity: "High",
    description: "Boxing fundamentals meets full-body conditioning. Bag work, pad drills, and bodyweight circuits that build coordination and serious stamina.",
    schedule: ["Mon 6:00 PM", "Wed 7:00 AM", "Fri 6:00 PM"],
    trainer: "Darnell Banks",
    spots: 14,
  },
  {
    id: "recover-reset",
    name: "Recover & Reset",
    category: "Recovery",
    duration: "45 min",
    intensity: "Low",
    description: "Guided mobility, foam rolling, and breathwork designed to accelerate recovery, reduce soreness, and keep you training at full capacity.",
    schedule: ["Tue 7:30 PM", "Thu 7:00 AM", "Sun 10:30 AM"],
    trainer: "Sofia Chen",
    spots: 18,
  },
];

export const trainers = [
  {
    name: "Marcus Reid",
    title: "Head Strength Coach",
    initials: "MR",
    specialty: "Powerlifting · Sports Performance",
    bio: "Former D1 athlete with ten years of coaching across the spectrum — first-day novices to competitive powerlifters. Marcus argues strength is the floor under everything else.",
    certifications: ["CSCS", "NSCA-CPT", "FMS Level 2"],
    classes: ["Iron Temple", "Velocity Cycle"],
    teaches: "Mon · Tue · Thu · Sat",
  },
  {
    name: "Sofia Chen",
    title: "Lead Wellness Coach",
    initials: "SC",
    specialty: "Yoga · Mobility · Recovery",
    bio: "200-hour RYT with a sports physical therapy background. Sofia smuggles clinical recovery science into every flow — your nervous system will notice first.",
    certifications: ["RYT-200", "NASM-CPT", "SFMA"],
    classes: ["Flow State", "Recover & Reset"],
    teaches: "Mon · Wed · Fri · Sun",
  },
  {
    name: "Darnell Banks",
    title: "HIIT & Combat Specialist",
    initials: "DB",
    specialty: "HIIT · Boxing · Conditioning",
    bio: "Golden Gloves amateur turned conditioning coach. Darnell's hour is hard — and there is a real, demonstrable chance you will love every second of it.",
    certifications: ["NASM-CPT", "USA Boxing Coach", "HIIT Specialist"],
    classes: ["HIIT Forge", "Combat Ready"],
    teaches: "Mon · Wed · Fri · Sat",
  },
];

export const pricingTiers = [
  {
    name: "Drop-In",
    price: "$28",
    period: "per class",
    description: "No commitment. Show up when you want, for any class on the schedule.",
    features: [
      "Single class access",
      "Any class on schedule",
      "Locker room & showers",
      "Towel service included",
    ],
    cta: "Book a Class",
    highlighted: false,
  },
  {
    name: "Monthly",
    price: "$149",
    period: "per month",
    description: "Unlimited classes, priority booking, and full access to all amenities.",
    features: [
      "Unlimited classes",
      "Priority class booking",
      "1 free guest pass / month",
      "Recovery lounge access",
      "APEX app included",
      "Free nutrition consult",
    ],
    cta: "Start Today",
    highlighted: true,
    badge: "Most Popular",
  },
  {
    name: "Annual",
    price: "$99",
    period: "per month",
    description: "Everything in Monthly — billed yearly. Save $600 and lock the rate forever.",
    features: [
      "Everything in Monthly",
      "2 free guest passes / month",
      "1 PT session / month ($80 value)",
      "Exclusive member events",
      "Rate locked forever",
    ],
    cta: "Best Value",
    highlighted: false,
    badge: "Save $600 / yr",
  },
];

export const testimonials = [
  {
    name: "Jasmine T.",
    initials: "JT",
    rating: 5,
    text: "I've tried every gym in Chicago. APEX is on another level. The classes are challenging but the coaches actually know your name. HIIT Forge has completely transformed my cardio in three months.",
    highlight: "Lost 18 lbs in 3 months",
    class: "HIIT Forge",
    date: "January 2026",
  },
  {
    name: "Ryan O.",
    initials: "RO",
    rating: 5,
    text: "Marcus in Iron Temple is the best strength coach I've worked with. He corrected form issues I had for years inside the first session. My squat went up 40 lbs in two months.",
    highlight: "Squat PR up 40 lbs",
    class: "Iron Temple",
    date: "February 2026",
  },
  {
    name: "Priya M.",
    initials: "PM",
    rating: 5,
    text: "Sofia's Flow State is the only reason I get through my week. The room is incredible and I've never been more flexible or less stressed. The recovery lounge is unreal.",
    highlight: "Zero injuries all season",
    class: "Flow State",
    date: "March 2026",
  },
];

export const stats = [
  { value: "1,247", label: "Active Members" },
  { value: "40+", label: "Classes / Week" },
  { value: "03", label: "Resident Coaches" },
  { value: "4.9", label: "Member Rating" },
];

export const features = [
  {
    title: "Programming, not workouts",
    desc: "Every hour is periodized and progressive — not a random sweat. Measurable progress in thirty days or your first month is on us.",
  },
  {
    title: "Recovery is part of the work",
    desc: "Recovery lounge, cold plunge, and dedicated reset classes. You return stronger, not flattened.",
  },
  {
    title: "Coaches are paid to coach",
    desc: "No salespeople disguised as trainers. Resident coaches lead the floor, run the classes, and remember your numbers.",
  },
  {
    title: "Honest pricing, no contracts",
    desc: "No joining fee. No hidden fees. Cancel any month with notice. The price you see is the price.",
  },
];
