export const siteConfig = {
  name: "APEX",
  fullName: "APEX Performance Studio",
  tagline: "An hour at the limit.",
  city: "West Chester",
  region: "PA",
  phone: "(610) 555-0174",
  email: "hello@apexperformancestudio.com",
  instagram: "@apexperformancepa",
  hours: {
    weekday: "5am to 10pm",
    saturday: "6am to 8pm",
    sunday: "7am to 6pm",
  },
};

export const classes = [
  {
    id: "hiit-forge",
    name: "HIIT Forge",
    category: "HIIT",
    duration: "45 min",
    intensity: "High",
    description: "Maximum effort, maximum results. Explosive intervals with active recovery to torch calories and build cardio capacity.",
    schedule: ["Mon 6:00 AM", "Wed 12:00 PM", "Fri 6:00 AM", "Sat 8:00 AM"],
    trainer: "Dani Banks",
    spots: 16,
  },
  {
    id: "iron-temple",
    name: "Iron Temple",
    category: "Strength",
    duration: "60 min",
    intensity: "Moderate to High",
    description: "Progressive strength on barbells, dumbbells, and compound patterns. Real-world power, programmed weekly.",
    schedule: ["Tue 7:00 AM", "Thu 6:00 PM", "Sat 10:00 AM"],
    trainer: "Maya Reid",
    spots: 12,
  },
  {
    id: "flow-state",
    name: "Flow State",
    category: "Yoga",
    duration: "60 min",
    intensity: "Low to Moderate",
    description: "Dynamic vinyasa that builds flexibility, balance, and mental clarity. Accessible for every level.",
    schedule: ["Mon 7:30 AM", "Wed 6:30 PM", "Fri 12:00 PM", "Sun 9:00 AM"],
    trainer: "Sofia Chen",
    spots: 20,
  },
  {
    id: "velocity-cycle",
    name: "Velocity Cycle",
    category: "Cycling",
    duration: "45 min",
    intensity: "High",
    description: "Rhythm-based indoor cycling set to curated playlists. Every pedal stroke is a step toward your best performance.",
    schedule: ["Tue 6:00 AM", "Thu 12:00 PM", "Sat 7:00 AM", "Sun 8:00 AM"],
    trainer: "Maya Reid",
    spots: 24,
  },
  {
    id: "combat-ready",
    name: "Combat Ready",
    category: "Boxing",
    duration: "50 min",
    intensity: "High",
    description: "Boxing fundamentals meet full-body conditioning. Bag work, pad drills, and bodyweight circuits build coordination and serious stamina.",
    schedule: ["Mon 6:00 PM", "Wed 7:00 AM", "Fri 6:00 PM"],
    trainer: "Dani Banks",
    spots: 14,
  },
  {
    id: "recover-reset",
    name: "Recover & Reset",
    category: "Recovery",
    duration: "45 min",
    intensity: "Low",
    description: "Guided mobility, foam rolling, and breathwork to accelerate recovery, reduce soreness, and keep you training at full capacity.",
    schedule: ["Tue 7:30 PM", "Thu 7:00 AM", "Sun 10:30 AM"],
    trainer: "Sofia Chen",
    spots: 18,
  },
];

export const trainers = [
  {
    name: "Maya Reid",
    title: "Head Strength Coach",
    initials: "MR",
    specialty: "Powerlifting · Sports Performance",
    bio: "Former D1 athlete with ten years of coaching across the spectrum. First-day novices to competitive powerlifters. Maya argues strength is the floor under everything else.",
    certifications: ["CSCS", "NSCA-CPT", "FMS Level 2"],
    classes: ["Iron Temple", "Velocity Cycle"],
    teaches: "Mon · Tue · Thu · Sat",
  },
  {
    name: "Sofia Chen",
    title: "Lead Wellness Coach",
    initials: "SC",
    specialty: "Yoga · Mobility · Recovery",
    bio: "200-hour RYT with a sports physical therapy background. Sofia smuggles clinical recovery science into every flow. Your nervous system will notice first.",
    certifications: ["RYT-200", "NASM-CPT", "SFMA"],
    classes: ["Flow State", "Recover & Reset"],
    teaches: "Mon · Wed · Fri · Sun",
  },
  {
    name: "Dani Banks",
    title: "HIIT & Combat Specialist",
    initials: "DB",
    specialty: "HIIT · Boxing · Conditioning",
    bio: "Golden Gloves amateur turned conditioning coach. Dani's hour is hard. There is a real, demonstrable chance you will love every second of it.",
    certifications: ["NASM-CPT", "USA Boxing Coach", "HIIT Specialist"],
    classes: ["HIIT Forge", "Combat Ready"],
    teaches: "Mon · Wed · Fri · Sat",
  },
];

export const pricingTiers = [
  {
    name: "Drop-In",
    price: "$28",
    period: "per class",
    description: "No commitment. Show up when you want, for any class on the schedule.",
    features: [
      "Single class access",
      "Any class on schedule",
      "Locker rooms and showers",
      "Towel service included",
    ],
    cta: "Book a class",
    highlighted: false,
  },
  {
    name: "Monthly",
    price: "$149",
    period: "per month",
    description: "Unlimited classes, priority booking, and full access to all amenities.",
    features: [
      "Unlimited classes",
      "Priority class booking",
      "1 free guest pass / month",
      "Recovery lounge access",
      "APEX app included",
      "Free nutrition consult",
    ],
    cta: "Start this month",
    highlighted: true,
  },
  {
    name: "Annual",
    price: "$99",
    period: "per month, billed yearly",
    description: "Everything in Monthly. Billed yearly. Save $600 and lock the rate forever.",
    features: [
      "Everything in Monthly",
      "2 free guest passes / month",
      "1 PT session / month ($80 value)",
      "Exclusive member events",
      "Rate locked forever",
    ],
    cta: "Lock the year",
    highlighted: false,
  },
];
